### PR TITLE
added a project file with Wasia's name to make an edf file

### PR DESCRIPTION
**Pull request by lucianacioca**

### CODE REVIEW

**Comment by jeffreycwitt** [comment]
It looks like you committed your oxygen project file into the repo as well (scta-projectfiles.xpr). Can you remove that and then resubmit. 

delete scta-projectfiles.xpr
then run 
git add -A
git commit -m "removed scta-projectfiles.xpr"
git push

**Comment by jeffreycwitt** [comment]
Or actually you don't need to delete the file, you can just move it to another directory. That way oxygen can still use it, but won't get added to the scta-projectfiles directory.

**Comment by lucianacioca** [comment]
Oh sorry, I will move it.

**Comment by lucianacioca** [comment]
is that ok?

**Pull request merged**
